import type { ThemeDefinition } from "@/features/theme/theme.types";

export const skyTheme: ThemeDefinition = {
  id: "sky",
  name: "Sky",
  statusBarStyle: "dark",
  colors: {
    background: "#F7FAFF",
    surface: "#FFFFFF",
    surfaceElevated: "#FFFFFF",
    surfaceSoft: "#EEF5FF",
    surfaceMuted: "#F3F6FA",
    textPrimary: "#14223A",
    textSecondary: "#6E7D92",
    textTertiary: "#9EABBD",
    primary: "#5D91F2",
    primarySoft: "#E5EFFF",
    border: "#DFE8F3",
    danger: "#D85E69",
    onPrimary: "#FFFFFF",
    chip: "#EDF4FF",
    input: "#FBFDFF",
    inputBorder: "#D9E4F2",
    navBackground: "#FFFFFF",
    navInactive: "#9AA8BA",
    shadow: "#6C84A6",
  },
  layout: {
    cardPadding: 18,
    screenHorizontal: 20,
    screenTop: 22,
    sectionGap: 24,
    tabBarHeight: 68,
  },
  spacing: {
    xs: 4,
    sm: 10,
    md: 16,
    lg: 24,
    xl: 32,
  },
  radius: {
    sm: 8,
    md: 14,
    lg: 20,
    xl: 26,
    full: 999,
  },
  shadow: { elevation: 3, offsetY: 5, opacity: 0.11, radius: 14 },
  typography: {
    display: {
      fontSize: 28,
      lineHeight: 36,
      fontWeight: "700",
      letterSpacing: -0.7,
    },
    title: {
      fontSize: 24,
      lineHeight: 32,
      fontWeight: "700",
      letterSpacing: -0.5,
    },
    heading: {
      fontSize: 18,
      lineHeight: 26,
      fontWeight: "700",
      letterSpacing: -0.2,
    },
    body: {
      fontSize: 15,
      lineHeight: 23,
      fontWeight: "400",
    },
    label: {
      fontSize: 14,
      lineHeight: 20,
      fontWeight: "600",
    },
    caption: {
      fontSize: 12,
      lineHeight: 18,
      fontWeight: "500",
    },
    meta: {
      fontSize: 11,
      lineHeight: 16,
      fontWeight: "500",
    },
  },
};
