import type { ThemeDefinition } from "@/features/theme/theme.types";

export const warmPaperTheme: ThemeDefinition = {
  id: "warm-paper",
  name: "Warm Paper",
  statusBarStyle: "dark",
  colors: {
    background: "#FAF5EB",
    surface: "#FFFDF8",
    surfaceElevated: "#FFFDF8",
    surfaceSoft: "#F2E6D2",
    surfaceMuted: "#F6EFE4",
    textPrimary: "#3D3028",
    textSecondary: "#78685D",
    textTertiary: "#A59588",
    primary: "#A66A45",
    primarySoft: "#F1D8C2",
    border: "#E7D8C5",
    danger: "#B84C55",
    onPrimary: "#FFFFFF",
    chip: "#F5E8D8",
    input: "#FFFCF7",
    inputBorder: "#E7D8C5",
    navBackground: "#FFFDF8",
    navInactive: "#A59588",
    shadow: "#8E735F",
  },
  layout: { cardPadding: 18, screenHorizontal: 20, screenTop: 22, sectionGap: 24, tabBarHeight: 68 },
  spacing: { xs: 4, sm: 8, md: 16, lg: 24, xl: 32 },
  radius: { sm: 10, md: 14, lg: 20, xl: 26, full: 999 },
  shadow: { elevation: 3, offsetY: 5, opacity: 0.11, radius: 14 },
  typography: {
    display: { fontSize: 28, lineHeight: 36, fontWeight: "700", letterSpacing: -0.7 },
    title: { fontSize: 24, lineHeight: 32, fontWeight: "700", letterSpacing: -0.5 },
    heading: { fontSize: 18, lineHeight: 26, fontWeight: "700", letterSpacing: -0.2 },
    body: { fontSize: 15, lineHeight: 23, fontWeight: "400" },
    label: { fontSize: 14, lineHeight: 20, fontWeight: "600" },
    caption: { fontSize: 12, lineHeight: 18, fontWeight: "500" },
    meta: { fontSize: 11, lineHeight: 16, fontWeight: "500" },
  },
};
